config/routes.rb
Rails.application.routes.draw do
  get "signup" => "users#new"
  # get "profile" => "users#show"\
  get "login" => "sessions#new"
  get "logout" => "sessions#destroy"
  get "/auth/:provider/callback" => "authentications#create"
  
  resources :sessions, except: [:index, :new, :edit, :update, :show, :destroy]
  resources :users, except: [:index] 
  resources :posts do 
    resources :comments
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # get 'about' => "sites#about"
  # Defines the root path route ("/")
  root 'posts#index'
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
    belongs_to :user
    
    validates :content, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :load_post
  before_action :load_comment, except: [:index, :new, :create]
  before_action :authenticate, except: [:index, :show]
  before_action :verify_ownership, except: [:index, :show, :new, :create]
  
  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new comment_params
    @comment.user = current_user
    @comment.post = @post
    
    if @comment.save 
      # redirect_to post_path(@post,@comment), notice: "Comment Created"
      redirect_to post_path(@post), notice: "Comment Created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @comment.update comment_params
      redirect_to post_path(@post), notice: "Comment updated"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def edit
  end

 
  def destroy
    @comment.delete
    redirect_to @post, alert: "Comment  deleted"
  end

  def index
  end

  def show
  end
  
  private
  
  def load_comment
    @comment = @post.comments.find params[:id]
  end
  
  def load_post
    @post = Post.find params[:post_id]
  end
  
  def comment_params
    params.require(:comment).permit(:content, :post_id, :mood)
  end
  
  def verify_ownership
    unless current_user == @comment.user
         redirect_to root_path, notice: "Not authorized"
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="card p-3 mt-2">
    <div class="d-flex justify-content-between align-items-end">
        <div class="user d-flex flex-row align-items-center">
            <img width="30" class="user-img rounded-circle mr-2" src="<%= current_user.avatar.attached? ? url_for(current_user.avatar) : "https://st3.depositphotos.com/15648834/17930/v/600/depositphotos_179308454-stock-illustration-unknown-person-silhouette-glasses-profile.jpg" %>">    
            <small class="font-weight-bold text-primary ms-1"> @<%= comment.user.username %> </small>  
        </div>
        <small class="font-weight-bold text-secondary">Mood: <%= comment.mood %></small>
    </div>
    <div class="action d-flex justify-content-between mt-2 align-items-center">

        <div class="reply px-4">
            <%= comment.content %>
        </div>

        <div class="icons align-items-center">
            <i class="fa fa-check-circle-o check-icon text-primary "> <%= link_to "Show", post_comment_path(@post, comment), class:"text-decoration-none" %></i>
            <i class="fa fa-check-circle-o check-icon text-primary"> <%= link_to "Edit", edit_post_comment_path(@post, comment), class:"text-decoration-none link-secondary" %></i>
            <!--<i class="fa fa-star-o text-danger">Destroy</i>-->
            
        </div>
    </div>
</div>

app/views/comments/_form.html.erb
<%= bootstrap_form_with(model: [@post, @comment], local: true) do |f| %>
    <%= f.text_area :content, hide_label: true, placeholder: "Type your tweet." %>
    <%= f.select :mood, ["Happy","Sad","Bored","Excited"], { label: "Choose your current mood:", wrapper: { class: 'has-warning', data: { foo: 'bar' } } }, { class: "selectpicker" } %>
    </br>
    <%= f.primary  @comment.persisted? ? 'Update':'Create' %>
<% end %>

app/views/comments/edit.html.erb
<% title "Edit Comment"  %>
<%= render 'form' %>

app/views/comments/new.html.erb
<% title "New Comment"  %>
<%= render 'form' %>

app/views/comments/show.html.erb
<!--create show-->
<br>
<%= render @comment%>
<div class="d-grid gap-2 d-md-flex justify-content-md-end">
<%= button_to "Delete", [@post, @comment], method: :delete, class: "btn btn-secondary btn-danger", form: { data: { turbo_confirm: 'Are you sure?' } }%>
</div>