config/routes.rb
Rails.application.routes.draw do
  get "signup" => "users#new"
  # get "profile" => "users#show"\
  get "login" => "sessions#new"
  get "logout" => "sessions#destroy"
  get "/auth/:provider/callback" => "authentications#create"
  
  resources :sessions, except: [:index, :new, :edit, :update, :show, :destroy]
  resources :users, except: [:index] 
  resources :posts do 
    resources :comments
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # get 'about' => "sites#about"
  # Defines the root path route ("/")
  root 'posts#index'
end

app/models/post.rb
class Post < ApplicationRecord
    validates :content, presence: true
    has_many :comments, dependent: :destroy

    # belongs_to :parent, class_name: "Post", optional: true
    belongs_to :user
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :load_post, except: [:index, :new, :create]
    before_action :authenticate, except: [:index, :show, :new]
    before_action :verify_ownership, except: [:index, :show, :create, :new]


    
    # GET   /posts         
    def index
        # logout
        @posts = Post.all
    end
    
    # GET   /posts/new
    def new
        @post = Post.new
    end
    
    # POST  /posts
    def create
        @post = Post.new post_params
        @post.user = current_user
        if @post.save
            redirect_to post_path(@post), notice: "Post created"
        else
            render :new, status: :unprocessable_entity
        end
    end
    
    # GET   /posts/:id
    def show
    end
    
    # GET   /posts/:id/edit
    def edit
    end
    
    #  PATCH (or PUT)  /posts/:id
    def update
        if @post.update post_params
            redirect_to @post, notice: "Post was updated."
        else
            render :edit, status: :unprocessable_entity
        end
    end
    
    #  DELETE /posts/:id
    def destroy
        @post.destroy
        redirect_to posts_path, alert: "Post  deleted"
    end
    
    def post_params
        params.require(:post).permit(:content, :mood, :country)
    end
    
    def verify_ownership
        unless current_user == @post.user
             redirect_to root_path, notice: "Not authorized"
        end
    end
    
    def load_post
        @post = Post.find params[:id]
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post.html.erb
<div class="card">
    <h5 class="card-header ">author: <%=@post.user.name %></h5>
    <div class="card-body">
        <h5 class="card-title d-flex justify-content-center">Mood: <%=@post.mood%> | Country: <%=@post.country%></h5>
        <p class="card-text d-flex justify-content-center"><%=@post.content%></h5>
        </p>
        <div id="switch" class="d-grid gap-2 d-md-flex justify-content-md-center">
            <%= link_to "Edit", edit_post_path(@post), class: "btn btn-primary"%>
            <%= button_to "Delete", @post, method: :delete, class: "btn btn-secondary btn-danger" %>
        </div>
    </div>
    
    <div class="container flex-row mb-3">
        <div class="row  d-flex justify-content-center">
            <div class="col-md-8">
                <div class="headings d-flex justify-content-between align-items-center mb-3">
                    <h5>Total Comments (<%= @post.comments.count %>)</h5>
                    <!--<div class="buttons">-->
                        <!--<a class="btn btn-primary" data-bs-toggle="collapse" href="#collapseExample" role="button" aria-expanded="true" aria-controls="collapseExample">-->
                        <!--    Show comments-->
                        <!--</a>-->
                    <!--</div>-->
                </div>
                <!--Comments block start Here-->
                <div >
                <!--<div class="collapse" id="collapseExample">-->
                    <div class="card card-body">
                        
                        <%=render @post.comments%>
                        
                        <div class="d-md-flex justify-content-md-center mt-2">
                            <%= link_to "New comment", new_post_comment_path(@post), class: "btn btn-primary", type:"button" %>
                        </div>
                    </div>
                </div>
                 <!--Comments block end here Here-->
            </div>
        </div>
    </div>
</div>
<br>

app/views/posts/edit.html.erb
<% title "Edit" %>
<%= bootstrap_form_with(model: @post, local: true) do |f| %>
    <%= f.text_area :content, hide_label: true, placeholder: "Type your tweet." %>
    <%= f.select :mood, ["Happy","Sad","Bored","Excited"], { label: "Choose your current mood:", wrapper: { class: 'has-warning', data: { foo: 'bar' } } }, { class: "selectpicker" } %>
    <%= f.select :country, ["USA","Japan","UK","Germany"], { label: "Choose your country of origin", wrapper: { class: 'has-warning', data: { foo: 'bar' } } }, { class: "selectpicker" } %>
    </br>
    <%= f.submit "Edit", class: "btn btn-primary btn-lg" %>
<% end %>

app/views/posts/index.html.erb
<% title "Public tweets" %>

<div class="my-3 p-3 bg-body rounded shadow-sm">
  <!-- <h6 class="border-bottom pb-2 mb-0">Recent public tweets</h6> -->
  
  <% @posts.each do |post|%>
  <div class="card">
    <h5 class="card-header">@<%=post.user.username%></h5>
    <div class="card-body">
      <h5 class="card-title">Mood: <%=post.mood%> | Country: <%=post.country%></h5>
      <p class="card-text"><%=post.content%></h5></p>
      <%= link_to "Show", post_path(post.id), class: "btn btn-primary"%>
    </div>
  </div>
  <br>
  <% end%>
  
</div>


<div class="d-grid gap-2">

  <%= link_to "New tweet", new_post_path, class: "btn btn-primary", type:"button" %>
</div>
</br>



<!--<div class="my-3 p-3 bg-body rounded shadow-sm">-->
<!--<h6 class="border-bottom pb-2 mb-0">Suggestions</h6>-->
<!--<div class="d-flex text-muted pt-3">-->
<!--  <svg class="bd-placeholder-img flex-shrink-0 me-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 32x32" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#007bff"></rect><text x="50%" y="50%" fill="#007bff" dy=".3em">32x32</text></svg>-->

<!--  <div class="pb-3 mb-0 small lh-sm border-bottom w-100">-->
<!--    <div class="d-flex justify-content-between">-->
<!--      <strong class="text-gray-dark">Full Name</strong>-->
<!--      <a href="#">Follow</a>-->
<!--    </div>-->
<!--    <span class="d-block">@username</span>-->
<!--  </div>-->
<!--</div>-->
<!--<div class="d-flex text-muted pt-3">-->
<!--  <svg class="bd-placeholder-img flex-shrink-0 me-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 32x32" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#007bff"></rect><text x="50%" y="50%" fill="#007bff" dy=".3em">32x32</text></svg>-->

<!--  <div class="pb-3 mb-0 small lh-sm border-bottom w-100">-->
<!--    <div class="d-flex justify-content-between">-->
<!--      <strong class="text-gray-dark">Full Name</strong>-->
<!--      <a href="#">Follow</a>-->
<!--    </div>-->
<!--    <span class="d-block">@username</span>-->
<!--  </div>-->
<!--</div>-->
<!--<div class="d-flex text-muted pt-3">-->
<!--  <svg class="bd-placeholder-img flex-shrink-0 me-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 32x32" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#007bff"></rect><text x="50%" y="50%" fill="#007bff" dy=".3em">32x32</text></svg>-->

<!--  <div class="pb-3 mb-0 small lh-sm border-bottom w-100">-->
<!--    <div class="d-flex justify-content-between">-->
<!--      <strong class="text-gray-dark">Full Name</strong>-->
<!--      <a href="#">Follow</a>-->
<!--    </div>-->
<!--    <span class="d-block">@username</span>-->
<!--  </div>-->
<!--</div>-->
<!--<small class="d-block text-end mt-3">-->
<!--  <a href="#">All suggestions</a>-->
<!--</small>-->
<!--</div>-->
  

app/views/posts/new.html.erb
<% title "New Tweet" %>
<%= bootstrap_form_with(model: @post, local: true) do |f| %>
    <%= f.text_area :content, hide_label: true, placeholder: "Type your tweet." %>
    <%= f.select :mood, ["Happy","Sad","Bored","Excited"], { label: "Choose your current mood:", wrapper: { class: 'has-warning', data: { foo: 'bar' } } }, { class: "selectpicker" } %>
    <%= f.select :country, ["USA","Japan","UK","Germany"], { label: "Choose your country of origin", wrapper: { class: 'has-warning', data: { foo: 'bar' } } }, { class: "selectpicker" } %>
    </br>
    <%= f.submit "Submit", class: "btn btn-primary btn-lg" %>
<% end %>

app/views/posts/show.html.erb
</br>
<%= render @post%>