config/routes.rb
Rails.application.routes.draw do
  get "signup" => "users#new"
  # get "profile" => "users#show"\
  get "login" => "sessions#new"
  get "logout" => "sessions#destroy"
  get "/auth/:provider/callback" => "authentications#create"
  
  resources :sessions, except: [:index, :new, :edit, :update, :show, :destroy]
  resources :users, except: [:index] 
  resources :posts do 
    resources :comments
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # get 'about' => "sites#about"
  # Defines the root path route ("/")
  root 'posts#index'
end

app/views/layouts/_navbar.html.erb
<!--Begnining of navbar-->

  <nav class="navbar navbar-expand-lg " style="background-color: #e3f2fd;">
  <div class="container-fluid">
    <%= link_to "Twitter", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarScroll">
      <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link active"%>
        </li>
        <li class="nav-item">
          <%= link_to "New tweet", new_post_path, class: "nav-link"%>
        </li>
      </ul>
      
      <ul class="navbar-nav mb-2 mb-md-0">
        <% if current_user %>
          <li class="nav-item">
            <%= link_to current_user.name, user_path(current_user), class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Logout", logout_path, class: "nav-link"%>
          </li>
        <% else  %>
          <li class="nav-item">
            <%= link_to "Login", login_path, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Up", signup_path, class: "nav-link"%>
          </li>
        <% end  %>
        </ul>
    </div>
  </div>
</nav>
  <!--end of navbar-->

app/views/layouts/_notice.html.erb
<% flash.each do |key, value| %>
      <div class="<%= flash_class(key)%>" role="alert">
            <%= value %>
      </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fbauth <%= " | "+ yield(:title) unless yield(:title).blank? %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="offcanvas.css" rel="stylesheet">
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  
  <%=render "layouts/navbar" %>
  <%=render "layouts/notice" %>
  <body>
    <main class="container">
      <% if @show_title %>
      <div id="title" class="row">
        <div class="col">
          </br>
          <h1><%= yield(:title) %></h1>
        </div>
      </div>
      <% end %>
    <%= yield %>
    </main>
  </body>
</html>